subconfigs = []

[api_keys]
# etherscan = "" (unset - no Etherscan API key)
# "goerli.etherscan" = "" (unset - no Goerli Etherscan API key)
# ...

[compiler.solc]
allow_paths = []
# evm_version (unset - let the compiler decide)
exclude_paths = ["node_modules", "venv", ".venv", "lib"]
include_paths = ["node_modules", "lib"]
remappings = [
    "contracts/=src/contracts/",
    "interfaces/=src/contracts/interfaces/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ds-test/=node_modules/ds-test/",
    "forge-std/=node_modules/forge-std/src/",
    "solady/=node_modules/solady/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/"
]

# target_version (unset - use the latest version)
via_IR = false

[compiler.solc.optimizer]
enabled = false
runs = 200

[compiler.solc.optimizer.details]
# peephole (unset - let the compiler decide)
# inliner (unset - let the compiler decide)
# jumpdest_remover (unset - let the compiler decide)
# order_literals (unset - let the compiler decide)
# deduplicate (unset - let the compiler decide)
# cse (unset - let the compiler decide)
# constant_optimizer (unset - let the compiler decide)
# simple_counter_for_loop_unchecked_increment (unset - let the compiler decide)

[compiler.solc.optimizer.details.yul_details]
# stack_allocation (unset - let the compiler decide)
# optimizer_steps (unset - let the compiler decide)

[deployment]
confirm_transactions = true
silent = false

[detector]

[detectors]
# exclude = ["3628"]
# only (unset - all detectors are enabled)
only = ["1"]
ignore_paths = ["venv", ".venv", "test", "src", "src/**/*"]
exclude_paths = ["node_modules", "lib", "src", "src/**/*"]

[general]
call_trace_options = [
    "contract_name", "function_name", "named_arguments", "status",
    "call_type", "value", "return_value", "error"
]
json_rpc_timeout = 15
link_format = "vscode://file/{path}:{line}:{col}"

[lsp]
compilation_delay = 1
code_lens.enable = false
detectors.enable = false


[printer]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
